apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}  # Uses the CI-built image
          ports:
            - containerPort: 5000
